apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wasp-api.fullname" . }}-config
  labels:
    {{- include "wasp-api.labels" . | nindent 4 }}
data:
  logLevel: {{ .Values.config.logLevel }}
  waspApiPort: {{ .Values.config.waspApiPort | quote }}
  redisHost: {{ include "wasp-api.redis.fullname" . }}
  redisPort: {{ .Values.config.redisPort | quote }}
  redisTlsEnabled: {{ .Values.config.redisTlsEnabled | quote }}
  thingsHost: {{ .Values.config.waspThingsHost }}
  thingsPort: {{ .Values.config.waspThingsPort | quote }}
  readingsHost: {{ .Values.config.waspReadingsHost }}
  readingsPort: {{ .Values.config.waspReadingsPort | quote }}
  usersHost: {{ .Values.config.waspUsersHost }}
  usersPort: {{ .Values.config.waspUsersPort | quote }}
